accounts/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = 'accounts'
urlpatterns = [
    path('signup',views.signup,name='signup'),
    path('profile',views.profile,name='profile'),
    path('update_profile',views.update_profile,name='update_profile'),
    path('logout/',views.logout_view,name='logout'),
    
    path('', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views
from carts.views import cart
from carts.views import add_cart
from carts.views import remove_cart

app_name = 'home'
urlpatterns = [
    path('',views.homepage,name='homeurl'),
    path('cart',cart, name='cart'),
    path('cat',views.category_view,name = 'category'),
    path('cat/<slug>',views.categoryslug,name = 'categoryslug'),
    path('<slug>',views.product_detail,name='product_detail'),
    path('cart/<addslug>',add_cart,name='add_cart'),
    path('cart/r/<removeslug>',remove_cart,name='remove_cart'),

]

pishrodarman/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('tickets/', include('ticketing.urls')),
    path('', include('home.urls')),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.
PREFERENCE_CHOICES = (
   ('first', 'first'),
   ('second', 'second'),
   ('third', 'third'),
)

class Product(models.Model):
    persian_name = models.CharField(max_length=150)
    english_name = models.CharField(max_length = 150)
    detail = models.TextField()
    category = models.ForeignKey('products_category',on_delete=models.CASCADE,related_name='+')
    reccomend = models.BooleanField(default=False)
    preference = models.CharField(choices=PREFERENCE_CHOICES, max_length=128, null=True,blank=True)
    price = models.PositiveIntegerField(default=0)
    backgroundcolor = models.CharField(max_length=6 , default='F75940')
    image = models.ImageField(default='products/default.png', upload_to='products')
    image_alt=models.CharField(default="image" ,max_length=500)
    date = models.DateTimeField(auto_now_add=False,auto_now = True)
    slug = models.SlugField(default='test')

    # brands
    def __str__(self):
        return self.persian_name
    def snippet(self):
        return self.detail[:50]+"..."

    def cltohex(self):
        return "#" + self.backgroundcolor


    def pricesn (self):
        pr = ''
        pricer = str(self.price)[::-1]
        la = pricer[-3:]
        l = (len(pricer)//3) + 1
        if len(pricer) % 3 == 0 :
            for i in range(l - 1):
                
                im = 3 * (i + 1)
                ii = pricer[im-3:im]
                if ii == la:
                    pr += ii
                else:
                    pr += ii + ','
        else:
            for i in range(l):
                im = 3 * (i + 1)
                ii = pricer[im-3:im]
                if len(ii) < 3:
                    pr += ii
                else:
                    pr += ii + ','
        return pr[::-1]
        
class products_category(models.Model):
    # product = models.ForeignKey('Product',on_delete=models.CASCADE,related_name='+',null =True , blank = True)
    title = models.CharField(max_length = 100)
    image = models.ImageField(default='categoty/default.png', upload_to='category', max_length=300)
    slug = models.SlugField(default='test')
    alt =models.CharField(default="image" ,max_length=500)

    def __str__(self):
        return self.title

home/views.py
from django.shortcuts import render,HttpResponse
from . import models
from carts.models import Cart
# Create your views here.
def homepage(request):
    products = models.Product.objects.all().order_by('-date')
    category = models.products_category.objects.all()
    last_products = models.Product.objects.all().order_by('-date')[:5]
    x = [1,2,3]

    if request.user.is_authenticated:
        try:
            cart = Cart.objects.get(id = request.user.id)

        except Cart.DoesNotExist:
            new_cart = Cart(id = request.user.id)
            new_cart.save()

        cart = Cart.objects.get(id = request.user.id)
        cart_items = cart.products.all()
        args = {'products':products,'x':x ,'lastProduct':last_products, 'category':category,'cartitems':cart_items } 
    else:
        args = {'products':products,'x':x ,'lastProduct':last_products, 'category':category}

    return render(request,'home/homepage.html',args)


def product_detail(request, slug):
    product = models.Product.objects.get(slug=slug)
    # return HttpResponse(english_name)
    if request.user.is_authenticated:
        try:
            cart = Cart.objects.get(id = request.user.id)

        except Cart.DoesNotExist:
            new_cart = Cart(id = request.user.id)
            new_cart.save()

        cart = Cart.objects.get(id = request.user.id)
        cart_items = cart.products.all()
        args = {'product':product ,'cartitems':cart_items }
    else:
        args = {'product':product}

    return render(request,'home/product_detail.html',args)



def category_view(request):
    category = models.products_category.objects.all()
    template = 'home/category.html'
    context = {'category':category}
    return render(request,template,context)

def categoryslug(request,slug):
    cat = models.products_category.objects.get(slug=slug)
    product = models.Product.objects.filter(category = cat)
    

    template = 'home/cat_item.html'
    context = {'cat':cat,'product':product}
    return render(request,template,context)

home/templates/base.html
{%load static%} {{block.super}}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0" />
    <meta name="apple-mobile-web-app-capable" content="yes" />

    <!-- load static -->


    <!-- link css in other htmls -->
    <link rel="stylesheet" href="{% static 'home/CSS/base/style.css' %}" type="text/css">
    <!-- link fonts -->
    <link rel="stylesheet" href="{% static 'home/CSS/fonts.css' %}" type="text/css"> {% block links %}{%endblock%}
    <title>
        {%block title%}title{%endblock%}

    </title>
</head>

<body>
    <nav>
        <div class="logo">
            <a href="{%url 'home:homeurl'%}">
                <h4>LOGO</h4>
            </a>
        </div>
        <ul class="nav-links">
            <li><a href="{% url 'home:homeurl' %}">خانه</a></li>
            <li><a href="#">محصولات</a></li>
            <li><a href="#">ارسال تیکت</a></li>
            <li><a href="#">فروشنده شوید</a></li>
        </ul>
        <div class="burger">
            <div class="line1"></div>
            <div class="line2"></div>
            <div class="line3"></div>
        </div>
    </nav>
    <div class="container">
        <div class="underheader">

            <div class="searchox">
                <form action="#">
                    <input type="text" placeholder="جستجو در میان کالا ها">
                </form>

                <img class="searchic" src="{% static 'home/icons/search.png' %}" alt="search icon">
            </div>
            {% if user.is_authenticated %}
            <a href="{%url 'accounts:profile'%}"><img src="{% static 'home/icons/user.png' %}" alt="user icon" class="useric"></a>
            {% else %}
            <a href="{% url 'accounts:login' %}"><img src="{% static 'home/icons/user.png' %}" alt="user icon" class="useric"></a>
            {% endif %}
            <a href="{% url 'home:cart' %}"><img src="{% static 'home/icons/basket.png' %}" alt="basket icon" class="basketic"></a>
            <div class="bascket_total">
                {% if items_total == None %}
                <p>0</p>
                {% else %}
                <p>{{ items_total }}</p>

                {% endif %}
            </div>
        </div>

    </div>

    <!-- content block -->
    {%block content%}{%endblock content%}
    <!-- footer -->
    <div class="footer">
        <ul class="footer_links">
            <li><a href="">سوالات متداول</a></li>
            <li><a href="">همکاری</a></li>
            <li><a href="">تماس با ما</a></li>
            <li><a href="">راهنما</a></li>
            <li><a href="">وبلاگ</a></li>
            <li><a href="">گزارش</a></li>
            <li><a href="">تماس با ما</a></li>
        </ul>
        <div class="copyright">
            <div class="line"></div>
            <p>
                کلیه حقوق این سایت متعلق به شرکت پیشرودرمان است.
            </p>
        </div>

    </div>
    <script src="{% static 'home/JS/app.js' %}"></script>
    <script>
        document.ontouchmove = function(event) {
            event.preventDefault();
        }
    </script>
    
    {% block scripts %}

    {% endblock scripts %}
</body>

</html>