home/urls.py
from django.urls import path
from . import views
from carts.views import cart
from carts.views import add_cart
from carts.views import remove_cart

app_name = 'home'
urlpatterns = [
    path('',views.homepage,name='homeurl'),
    path('cart',cart, name='cart'),
    path('cat',views.category_view,name = 'category'),
    path('cat/<slug>',views.categoryslug,name = 'categoryslug'),
    path('<slug>',views.product_detail,name='product_detail'),
    path('cart/<addslug>',add_cart,name='add_cart'),
    path('cart/r/<removeslug>',remove_cart,name='remove_cart'),

]

pishrodarman/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('tickets/', include('ticketing.urls')),
    path('', include('home.urls')),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.
PREFERENCE_CHOICES = (
   ('first', 'first'),
   ('second', 'second'),
   ('third', 'third'),
)

class Product(models.Model):
    persian_name = models.CharField(max_length=150)
    english_name = models.CharField(max_length = 150)
    detail = models.TextField()
    category = models.ForeignKey('products_category',on_delete=models.CASCADE,related_name='+')
    reccomend = models.BooleanField(default=False)
    preference = models.CharField(choices=PREFERENCE_CHOICES, max_length=128, null=True,blank=True)
    price = models.PositiveIntegerField(default=0)
    backgroundcolor = models.CharField(max_length=6 , default='F75940')
    image = models.ImageField(default='products/default.png', upload_to='products')
    image_alt=models.CharField(default="image" ,max_length=500)
    date = models.DateTimeField(auto_now_add=False,auto_now = True)
    slug = models.SlugField(default='test')

    # brands
    def __str__(self):
        return self.persian_name
    def snippet(self):
        return self.detail[:50]+"..."

    def cltohex(self):
        return "#" + self.backgroundcolor


    def pricesn (self):
        pr = ''
        pricer = str(self.price)[::-1]
        la = pricer[-3:]
        l = (len(pricer)//3) + 1
        if len(pricer) % 3 == 0 :
            for i in range(l - 1):
                
                im = 3 * (i + 1)
                ii = pricer[im-3:im]
                if ii == la:
                    pr += ii
                else:
                    pr += ii + ','
        else:
            for i in range(l):
                im = 3 * (i + 1)
                ii = pricer[im-3:im]
                if len(ii) < 3:
                    pr += ii
                else:
                    pr += ii + ','
        return pr[::-1]
        
class products_category(models.Model):
    # product = models.ForeignKey('Product',on_delete=models.CASCADE,related_name='+',null =True , blank = True)
    title = models.CharField(max_length = 100)
    image = models.ImageField(default='categoty/default.png', upload_to='category', max_length=300)
    slug = models.SlugField(default='test')
    alt =models.CharField(default="image" ,max_length=500)

    def __str__(self):
        return self.title

home/views.py
from django.shortcuts import render,HttpResponse
from . import models
from carts.models import Cart
# Create your views here.
def homepage(request):
    products = models.Product.objects.all().order_by('-date')
    category = models.products_category.objects.all()
    last_products = models.Product.objects.all().order_by('-date')[:5]
    x = [1,2,3]

    if request.user.is_authenticated:
        try:
            cart = Cart.objects.get(id = request.user.id)

        except Cart.DoesNotExist:
            new_cart = Cart(id = request.user.id)
            new_cart.save()

        cart = Cart.objects.get(id = request.user.id)
        cart_items = cart.products.all()
        args = {'products':products,'x':x ,'lastProduct':last_products, 'category':category,'cartitems':cart_items } 
    else:
        args = {'products':products,'x':x ,'lastProduct':last_products, 'category':category}

    return render(request,'home/homepage.html',args)


def product_detail(request, slug):
    product = models.Product.objects.get(slug=slug)
    # return HttpResponse(english_name)
    if request.user.is_authenticated:
        try:
            cart = Cart.objects.get(id = request.user.id)

        except Cart.DoesNotExist:
            new_cart = Cart(id = request.user.id)
            new_cart.save()

        cart = Cart.objects.get(id = request.user.id)
        cart_items = cart.products.all()
        args = {'product':product ,'cartitems':cart_items }
    else:
        args = {'product':product}

    return render(request,'home/product_detail.html',args)



def category_view(request):
    category = models.products_category.objects.all()
    template = 'home/category.html'
    context = {'category':category}
    return render(request,template,context)

def categoryslug(request,slug):
    cat = models.products_category.objects.get(slug=slug)
    product = models.Product.objects.filter(category = cat)
    

    template = 'home/cat_item.html'
    context = {'cat':cat,'product':product}
    return render(request,template,context)

home/templates/home/cat_item.html
{% extends 'base.html' %} {% block links %} {% load static %}
<link rel="stylesheet" href="{% static 'home/CSS/category/style.css' %}"> {% endblock links %} {% block content %}
<div class="catitems_container">


    {% for item in product %}
    <div class="catitem" style="background-color: {{item.cltohex}};">
        <img src="{{item.image.url}}" alt="{{item.alt}}">
        <h1>
            {{item.persian_name}}
        </h1>
        <a href="{% url 'home:product_detail' item.slug %}"> <button class="detail">جزئیات</button> </a>
        <a class="diva" href="{% url 'home:product_detail' item.slug %}"></a>
    </div>
    {% endfor %}


</div>
{% endblock content %}

home/templates/home/category.html
{% extends 'base.html' %}
{% block links %}
{% load static %}
<link rel="stylesheet" href="{% static 'home/CSS/category/style.css' %}">
{% endblock links %}
{% block content %}
<div class="cat_container">

    {% for category in category %}
    <div class="catitem">
        <img src="{{category.image.url}}" alt="{{category.alt}}">
        <h1>
            {{category.title}}
        </h1>
        <a href="{% url 'home:categoryslug' category.slug %}"></a>
    </div>
    {% endfor %}

</div>
{% endblock content %}

home/templates/home/homepage.html
{%extends "base.html"%} {%load static%} {%block title%}home{%endblock%} {% block links %} {%endblock%} {%block content%}

<div class="homecontainer">
    <!-- slider -->
    <!-- slider -->
    <div class="headslider">
        {% for product in products %} {% if product.reccomend %}
        <div class="slide" style="background-color: {{product.cltohex}};">
            <div class="items">
                <div class="itemsdetail">
                    <h1>
                        {{product.persian_name}}
                    </h1>
                    <p>{{product.snippet}}</p>
                    <div class="buttons">
                        <a href="{% url 'home:product_detail' product.slug %}"> <button class="detail">جزئیات</button> </a>
                        {% if user.is_authenticated %} {% if product in cartitems %}
                        <a href="{% url 'home:remove_cart' product.slug %}"><img src="{% static 'home/icons/remove.png' %}" alt="" class="addtobasket"></a>

                        {%else%}
                        <a href="{% url 'home:add_cart' product.slug %}"><img src="{% static 'home/icons/addtobasket.png' %}" alt="" class="addtobasket"></a>
                        {%endif%} {% else %}
                        <a href="{% url 'accounts:login'%}"><img src="{% static 'home/icons/addtobasket.png' %}" alt="" class="addtobasket"></a>
                        {% endif %}
                    </div>
                    <p class="price">قیمت : {{product.pricesn}} ریال</p>
                </div>
                <div class="itemimg">
                    <img src="media/{{MEDIA_URL}}{{product.image}}" alt="{{lp.image_lt}}">
                </div>
            </div>
        </div>
        {% endif %} {% endfor %}
    </div>
    <div class="headsliderlarge">
        <div class="leftslider">
            {% for product in products %} {% if product.reccomend %} {%if product.preference == 'first'%}
            <div class="slide" style="background-color: {{product.cltohex}};">
                <div class="items">
                    <div class="itemsdetail">
                        <h1>
                            {{product.persian_name}}
                        </h1>
                        <p>{{product.snippet}}</p>
                        <div class="buttons">
                            <a href="{% url 'home:product_detail' product.slug %}"> <button class="detail">جزئیات</button> </a>
                            {% if user.is_authenticated %} {% if product in cartitems %}
                            <a href="{% url 'home:remove_cart' product.slug %}"><img src="{% static 'home/icons/remove.png' %}" alt="" class="addtobasket"></a>

                            {%else%}
                            <a href="{% url 'home:add_cart' product.slug %}"><img src="{% static 'home/icons/addtobasket.png' %}" alt="" class="addtobasket"></a>
                            {%endif%} {% else %}
                            <a href="{% url 'accounts:login'%}"><img src="{% static 'home/icons/addtobasket.png' %}" alt="" class="addtobasket"></a>
                            {% endif %}
                        </div>
                        <p class="price">قیمت : {{product.pricesn}} ریال</p>
                    </div>
                    <div class="itemimg">
                        <img src="media/{{MEDIA_URL}}{{product.image}}" alt="{{lp.image_lt}}">
                    </div>
                </div>
            </div>
            {% endif %}{% endif %} {% endfor %}</div>
        <div class="rightslider">
            {% for product in products %} {% if product.reccomend %} {%if product.preference != 'first'%}

            <div class="slide " style="background-color: {{product.cltohex}};">
                <div class="items">
                    <div class="itemsdetail">
                        <h1>
                            {{product.persian_name}}
                        </h1>
                        <p>{{product.snippet}}</p>
                        <div class="buttons">
                            <a href="{% url 'home:product_detail' product.slug %}"> <button class="detail">جزئیات</button> </a>
                            {% if user.is_authenticated %} {% if product in cartitems %}
                            <a href="{% url 'home:remove_cart' product.slug %}"><img src="{% static 'home/icons/remove.png' %}" alt="" class="addtobasket"></a>

                            {%else%}
                            <a href="{% url 'home:add_cart' product.slug %}"><img src="{% static 'home/icons/addtobasket.png' %}" alt="" class="addtobasket"></a>
                            {%endif%} {% else %}
                            <a href="{% url 'accounts:login'%}"><img src="{% static 'home/icons/addtobasket.png' %}" alt="" class="addtobasket"></a>
                            {% endif %}
                        </div>
                        <p class="price">قیمت : {{product.pricesn}} ریال</p>
                    </div>
                    <div class="itemimg">
                        <img src="media/{{MEDIA_URL}}{{product.image}}" alt="{{lp.image_lt}}">
                    </div>
                </div>
            </div>
            {% endif %} {% endif %} {% endfor %}</div>
    </div>




</div>
<div class="last-products">
    <h1>آخرین محصولات</h1>
    <div class="line">
    </div>
    <div class="products">
        {% for product in lastProduct %}
        <div class="product">
            <img src="{{product.image.url}}" alt="{{product.image_lt}}">
            <div class="line"></div>
            <h1>{{product.persian_name}}</h1>
            <p>{{product.snippet}}</p>
            <div class="btns">
                <a href="{% url 'home:product_detail' product.slug %}"> <button class="detail">جزئیات</button> </a>

                {% if user.is_authenticated %} {% if product in cartitems %}
                <a href="{% url 'home:remove_cart' product.slug %}"><img src="{% static 'home/icons/remove.png' %}" alt="" class="addtobasket"></a>

                {%else%}
                <a href="{% url 'home:add_cart' product.slug %}"><img src="{% static 'home/icons/addtobasket.png' %}" alt="" class="addtobasket"></a>
                {%endif%} {% else %}
                <a href="{% url 'accounts:login'%}"><img src="{% static 'home/icons/addtobasket.png' %}" alt="" class="addtobasket"></a>
                {% endif %}
                <p class="price">قیمت : {{product.pricesn}} ریال</p>

            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div class="category">
    <h1>دسته بندی محصولات</h1>
    <div class="line"></div>
    <div class="cat">
        {% for cat in category %}
        <div class="cat_item">
            <img src="media/{{MEDIA_URL}}{{cat.image}}" alt="">
            <h3>{{cat.title}}</h3>
            <a href="{% url 'home:categoryslug' cat.slug %}"></a>

        </div>
        {% endfor %}
    </div>
</div>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'home/JS/home.js' %}"></script>
<script src="{% static 'home/JS/functions.js' %}"></script>

{%endblock content%}

home/templates/home/product_detail.html
{% extends 'base.html' %} {%load static%} {% block title %} {{product.persian_name}} {% endblock title %} {% block links %}
<link rel="stylesheet" href="{% static 'home/CSS/prodect_detail/prodect_detail.css' %}" type="text/css"> {% endblock links %} {% block content %}
<div class="unique_prodect_detail">
    <h1>{{product.persian_name}}</h1>
    <div class="line"></div>
    <div class="prodect">
        <img src="media/{{MEDIA_URL}}{{product.image}}" alt="" class="first">
        <div class="un">
            <div class="category">
                <p>دسته بندی</p>
                <h2>{{product.category}}</h2>
            </div>
            <div class="basketbtn">
                {% if user.is_authenticated %}
                        {% if product in cartitems %}
                        <a href="{% url 'home:remove_cart' product.slug %}"><img src="{% static 'home/icons/remove.png' %}" alt="" class="addtobasket"></a>

                        {%else%}
                        <a href="{% url 'home:add_cart' product.slug %}"><img src="{% static 'home/icons/addtobasket.png' %}" alt="" class="addtobasket"></a>
                        {%endif%}
                        {% else %}
                        <a href="{% url 'accounts:login'%}"><img src="{% static 'home/icons/addtobasket.png' %}" alt="" class="addtobasket"></a>
                        {% endif %}
            </div>
        </div>
        <div class="price">
            <p>{{product.pricesn}} ریال</p>
        </div>
        <p>{{product.detail}}</p>
    </div>
</div>
{% endblock content %}