accounts/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = 'accounts'
urlpatterns = [
    path('signup',views.signup,name='signup'),
    path('profile',views.profile,name='profile'),
    path('update_profile',views.update_profile,name='update_profile'),
    path('logout/',views.logout_view,name='logout'),
    
    path('', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views
from carts.views import cart
from carts.views import add_cart
from carts.views import remove_cart

app_name = 'home'
urlpatterns = [
    path('',views.homepage,name='homeurl'),
    path('cart',cart, name='cart'),
    path('cat',views.category_view,name = 'category'),
    path('cat/<slug>',views.categoryslug,name = 'categoryslug'),
    path('<slug>',views.product_detail,name='product_detail'),
    path('cart/<addslug>',add_cart,name='add_cart'),
    path('cart/r/<removeslug>',remove_cart,name='remove_cart'),

]

pishrodarman/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('tickets/', include('ticketing.urls')),
    path('', include('home.urls')),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phoneNumber = models.CharField(max_length=12,blank=True,null=True)
    location = models.CharField(max_length=400,blank=True,null=True)
    email = models.EmailField(blank=True,null=True)
    fullname = models.CharField(max_length=30 ,blank=True,null=True)


    def __str__(self):
        return self.user.username
    

accounts/forms.py
from django import forms
from django.contrib.auth import login,authenticate
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm, UsernameField
from django.contrib.auth.models import User
from .models import UserProfile

class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=30, required=True,label='نام کاربری*')
    password1 = forms.CharField(max_length=30, required=True,label='رمز عبور*',widget=forms.PasswordInput)
    password2 = forms.CharField(max_length=30, required=True,label='تایید رمز عبور*',widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ["username", "password1","password2"]
  


class UserProfileForm(forms.ModelForm):
    phoneNumber = forms.CharField(label='شماره تماس' ,max_length=12, required=False,widget=forms.NumberInput())
    location = forms.CharField(label='آدرس', max_length=100, required=False)
    email = forms.EmailField(label='ایمیل', required=False)
    fullname = forms.CharField(max_length=30,label='نام و نام خانوادگی', required=False)


    class Meta:
        model = UserProfile
        fields = ["phoneNumber","location","fullname" , "email"]

accounts/views.py
from django.shortcuts import render, redirect, HttpResponse
from . import forms
from . import models
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


def signup(request):
    if request.method == "POST":
            form = forms.RegisterForm(request.POST)
            form1 = forms.UserProfileForm(request.POST)
            if form.is_valid() and form1.is_valid():
                user = form.save()
                profile = form1.save(commit=False)
                profile.user = user
                profile.save()
                new_user = authenticate(username=form.cleaned_data['username'],password=form.cleaned_data['password1'],)
                
                login(request,new_user)
                return redirect("/")
    else:
        form = forms.RegisterForm()
        form1 = forms.UserProfileForm()

    return render(request,'accounts/user_signup.html',{"form":form,"form1":form1 })



@login_required(login_url = 'accounts/login')
def profile(request):
    profile = models.UserProfile.objects.get(user=request.user)
    return render(request,'accounts/profile.html',{'profile':profile})

def logout_view(request):
    logout(request)
    return render(request,'accounts/logout.html')


def update_profile(request):
    profile = models.UserProfile.objects.get(user=request.user)


    if request.method == "POST":
        form1 = forms.UserProfileForm(request.POST , instance=profile)


        if form1.is_valid():

            update1 = form1.save(commit=False)
            update1.user = request.user
            update1.save()
            return redirect("/")
    
    else:
        form1 = forms.UserProfileForm(instance=profile)



    return render(request,'accounts/update_profile.html',{'form1':form1})

accounts/templates/accounts/logout.html
{% extends 'base.html' %} {% block content %}{% block links %} {% load static %}
<link rel="stylesheet" href="{% static 'accounts/CSS/registration/registration.css' %}"> {% endblock links %}
<div class="logout_container">
    <div class="success">
        <p class="logoutt">خروج با موفقیت انجام گردید.</p>
        <p class="login">از اینجا وارد شوید:
            <a href="{% url 'accounts:login' %}">ورود</a>
        </p>
    </div>

</div>

{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}  {% block links %}{% load static %}
<link rel="stylesheet" href="{% static 'accounts/CSS/profile.css' %}" type="text/css"> {% endblock links %} {% block content %}

<div class="profile_unique">
    <div class="side">
        <div class="prof_info">
            <img src="" alt="">
            <div class="user">
                <h1>{% if profile.fullname %}
                {{profile.fullname}}{% else %}<a href="{% url 'accounts:update_profile' %}">تکمیل پروفایل</a>
                {% endif %}</h1><br>
                <p>{{profile.email}}</p>
            </div>
        </div>
        <ul>
            <div class="line"></div>
            <li><a href="">سفارشات</a></li>
            <div class="line"></div>
            <li><a href="">تاریخچه خرید</a></li>
            <div class="line"></div>
            <li><a href="">تماس با ما</a></li>
            <div class="line"></div>
            <li><a href="{% url 'accounts:logout' %}">خروج</a></li>
            <div class="line"></div>
        </ul>
    </div>
    <div class="cont">

        <h1 class="title">اطلاعات کاربری</h1>
        <div class="userinformation">
            <div class="info">
                <div class="username">
                    <h1>نام کاربری</h1>
                    <h2>{{user.username}}</h2>
                </div>
                <div class="useremail">
                    <h1>آدرس ایمیل</h1>
                    <h2>
                    {% if profile.email %} {{profile.email}} {% else %}
                        <a href="{% url 'accounts:update_profile' %}">تکمیل پروفایل</a> {% endif %}
                    </h2>
                </div>
                <div class="userphoneNumber">
                    <h1>شماره همراه</h1>
                    <h2>
                        {% if profile.phoneNumber %} {{profile.phoneNumber}} {% else %}
                        <a href="{% url 'accounts:update_profile' %}">تکمیل پروفایل</a> {% endif %}
                    </h2>
                </div>
                <div class="userlocation">
                    <h1>آدرس</h1>
                    <h2>
                        {% if profile.location %} {{profile.location}} {% else %}
                        <a href="{% url 'accounts:update_profile' %}">تکمیل پروفایل</a> {% endif %}
                    </h2>
                </div>
            </div>
            <div class="update_profile"><a href="{% url 'accounts:update_profile' %}">تغییر اطلاعات</a></div>
        </div>

    </div>
</div>
{% endblock content %}

accounts/templates/accounts/update_profile.html
{% extends 'base.html' %}{% block links %}{% load static %}
<link rel="stylesheet" href="{% static 'accounts/CSS/profile.css' %}" type="text/css"> {% endblock links %} {% block content %}
<div class="updateprofile_container">
    <form action="{% url 'accounts:update_profile' %}" method="POST">
        {{form1}}

        {% csrf_token %}
        <button type="submit">بروز رسانی</button>
    </form>
</div>
{% endblock content %}

accounts/templates/accounts/user_signup.html
{% extends 'base.html' %} {% block title %} signup {% endblock title %} {% block links %} {% load static %}
<link rel="stylesheet" href="{% static 'accounts/CSS/registration/registration.css' %}"> {% endblock links %} {% block content %}
<div class="signup_container">
    <div class="signup">
        <form action="" method="POST">
            {{form}} {% csrf_token %}{{form1}} 
            <button type="submit">ثبت نام</button>
 
        </form>
    </div>
</div>
{% endblock content %}